# Default values for travigo-data-importer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  connectionStringSecret: travigo-mongodb-admin-travigo
  database: travigo

redis:
  address: "redis-headless.redis:6379"
  passwordSecret: redis-password

elasticsearch:
  address: "https://primary-es-http.elastic:9200"
  accountSecret: "travigo-elasticsearch-user"

bods:
  apiKeySecret: travigo-bods-api

ie_nationaltransport:
  apiKeySecret: travigo-ie-nationaltransport-api

nationalRail:
  credentialsSecret: travigo-nationalrail-credentials
  networkRailCredentialsSecret: travigo-networkrail-credentials

image:
  repository: ghcr.io/travigo/travigo
  pullPolicy: Always
  tag: main

cronjobs:
  - name: travelinenoc
    schedule: "0 2 * * 0"
    args: ["data-importer", "dataset", "--id", "gb-traveline-noc"]
  - name: nationalrail-toc
    schedule: "10 2 * * 0"
    args: ["data-importer", "dataset", "--id", "gb-nationalrail-toc"]
  - name: nationalrail-timetable
    schedule: "15 5 * * *"
    args: ["data-importer", "dataset", "--id", "gb-nationalrail-timetable"]
  - name: naptan
    schedule: "0 3 * * 6"
    args: ["data-importer", "dataset", "--id", "gb-dft-naptan"]
  - name: networkrail-corpus
    schedule: "30 4 * * 6"
    args: ["data-importer", "dataset", "--id", "gb-networkrail-corpus"]
  - name: gb-bods-gtfs-timetable
    schedule: "20 6 * * *"
    args: ["data-importer", "dataset", "--id", "gb-dft-bods-gtfs-schedule"]
    batchburst: true
  - name: ie-gtfs-schedule
    schedule: "50 6 * * *"
    args: ["data-importer", "dataset", "--id", "ie-gtfs-schedule"]
    batchburst: true
  - name: us-nyc-subway-schedule
    schedule: "0 8 * * *"
    args: ["data-importer", "dataset", "--id", "us-nyc-subway-schedule"]
    batchburst: true
  - name: fr-ilevia-lille-gtfs-schedule
    schedule: "0 8 * * *"
    args: ["data-importer", "dataset", "--id", "fr-ilevia-lille-gtfs-sc"]
    batchburst: true
  - name: temp-indexer-stops
    schedule: "50 3 * * 6"
    args: [ "indexer", "stops" ]

deployments:
  # TODO make sirivm ignore if its handled by gtfs / make gtfs the priority - then go back to 10s
  - name: sirivm-all
    args: ["data-importer", "dataset", "--id", "gb-dft-bods-sirivm-all", "--repeat-every", "30s"]
  - name: gb-bods-gtfs-rt
    args: ["data-importer", "dataset", "--id", "gb-dft-bods-gtfs-realtime", "--repeat-every", "10s"]
  - name: ie-gtfs-realtime
    args: ["data-importer", "dataset", "--id", "ie-gtfs-realtime", "--repeat-every", "90s"]
  - name: fr-ilevia-lille-gtfs-rt
    args: ["data-importer", "dataset", "--id", "fr-ilevia-lille-gtfs-realtime", "--repeat-every", "90s"]
  # - name: us-nyc-subway-realtime-numbers
  #   args: ["data-importer", "dataset", "--id", "us-nyc-subway-relatime-1-2-3-4-5-6-7", "--repeat-every", "60s"]

resources: {}
podAnnotations: {}
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""