apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travigo-realtime.fullname" . }}-runner
  labels:
    {{- include "travigo-realtime.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "travigo-realtime.selectorLabels" . | nindent 6 }}
      appModule: runner
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "travigo-realtime.selectorLabels" . | nindent 8 }}
        appModule: runner
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "travigo-realtime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["run"]
          ports:
            - name: http
              containerPort: 3333
              protocol: TCP
          env:
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: BRITBUS_LOG_FORMAT
              value: JSON
            - name: BRITBUS_MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.database.connectionStringSecret }}
                  key: connectionString.standard
                  optional: false
            - name: BRITBUS_MONGODB_DATABASE
              value: {{ $.Values.database.database }}
            - name: BRITBUS_REDIS_ADDRESS
              value: {{ $.Values.redis.address }}
            - name: BRITBUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.redis.passwordSecret }}
                  key: password
                  optional: false
            - name: BRITBUS_ELASTICSEARCH_ADDRESS
              value: {{ $.Values.elasticsearch.address }}
            - name: BRITBUS_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticsearch.accountSecret }}
                  key: username
                  optional: false
            - name: BRITBUS_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticsearch.accountSecret }}
                  key: password
                  optional: false
          resources:
            {{- toYaml .Values.runner.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
