apiVersion: v1
kind: Service
metadata:
  name: {{ include "travigo-stats.fullname" . }}-webapi
  labels:
    {{- include "travigo-stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web_api.service.type }}
  ports:
    - port: {{ .Values.web_api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "travigo-stats.selectorLabels" . | nindent 4 }}
