apiVersion: apps/v1
kind: Deployment
metadata:
  name: monstache
  labels:
    app: monstache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monstache
  template:
    metadata:
      labels:
        app: monstache
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: monstache-config
      containers:
      - name: monstache
        image: rwynn/monstache:rel6
        args:
        - "-f"
        - "/data/config.toml"
        volumeMounts:
        - name: config-volume
          mountPath: /data/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monstache-config
data:
  config.toml: |
    mongo-url = "mongodb://travigo:UEiPGBbx4aEuhXNKxMSWKqCmpAblQKzUS8GqtRoZb0lP7i3szpADtBTsrlxTaGuo@travigo-mongodb-0.travigo-mongodb-svc.default.svc.cluster.local:27017/admin?replicaSet=travigo-mongodb&ssl=false"

    namespace-regex = '^travigo\.stops$'

    direct-read-namespaces = ["travigo.stops"]
    # change-stream-namespaces = ["mydb.mycollection", "db.collection", "test.test"]

    elasticsearch-urls = ["https://primary-es-http.elastic:9200"]
    elasticsearch-user = "travigo"
    elasticsearch-password = "TOPsecretTRAVIgoPassword1995!"
    elasticsearch-validate-pem-file = false
  
    # do not start processing at the beginning of the MongoDB oplog
    # if you set the replay to true you may see version conflict messages
    # in the log if you had synced previously. This just means that you are replaying old docs which are already
    # in Elasticsearch with a newer version. Elasticsearch is preventing the old docs from overwriting new ones.
    replay = false
    # resume processing from a timestamp saved in a previous run
    resume = true
    # do not validate that progress timestamps have been saved
    resume-write-unsafe = false
    # override the name under which resume state is saved
    resume-name = "default"
    # use a custom resume strategy (tokens) instead of the default strategy (timestamps)
    # tokens work with MongoDB API 3.6+ while timestamps work only with MongoDB API 4.0+
    resume-strategy = 1
    
    verbose = true
    exit-after-direct-reads = false