apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travigo-web-api.fullname" . }}
  labels:
    {{- include "travigo-web-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "travigo-web-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "travigo-web-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "travigo-web-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TRAVIGO_LOG_FORMAT
              value: JSON
            - name: TRAVIGO_DEBUG
              value: "YES"
            - name: TRAVIGO_MONGODB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.connectionStringSecret }}
                  key: connectionString.standard
                  optional: false
            - name: TRAVIGO_MONGODB_DATABASE
              value: {{ .Values.database.database }}
            - name: TRAVIGO_BODS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.bods.apiKeySecret }}
                  key: api_key
                  optional: false
            - name: TRAVIGO_ELASTICSEARCH_ADDRESS
              value: {{ $.Values.elasticsearch.address }}
            - name: TRAVIGO_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticsearch.accountSecret }}
                  key: username
                  optional: false
            - name: TRAVIGO_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.elasticsearch.accountSecret }}
                  key: password
                  optional: false
            - name: TRAVIGO_REDIS_ADDRESS
              value: {{ $.Values.redis.address }}
            - name: TRAVIGO_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.redis.passwordSecret }}
                  key: password
                  optional: false
            - name: TRAVIGO_LDBWS_GATEWAY_ENDPOINT
              value: "http://ldbws-gatewway-ldbws-gateway.default.svc.cluster.local:80"
            - name: TRAVIGO_TFL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.tfl.apiKeySecret }}
                  key: api_key
                  optional: false
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          args:
            - "web-api"
            - "run"
            - "--listen"
            - ":80"
          livenessProbe:
            httpGet:
              path: /core/version
              port: http
          readinessProbe:
            httpGet:
              path: /core/version
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
