apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "britbus-realtime.fullname" . }}-cleaner
  labels:
    {{- include "britbus-realtime.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "britbus-realtime.selectorLabels" . | nindent 6 }}
      appModule: cleaner
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "britbus-realtime.selectorLabels" . | nindent 8 }}
        appModule: cleaner
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "britbus-realtime.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["cleaner"]
          env:
            {{- with .env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: BRITBUS_LOG_FORMAT
              value: JSON
            - name: BRITBUS_REDIS_ADDRESS
              value: {{ $.Values.redis.address }}
            - name: BRITBUS_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.redis.passwordSecret }}
                  key: password
                  optional: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
